# Complete manual annotations for all 10 example files
MANUAL_ANNOTATIONS = {
    "example_01_theft.txt": {
        "court or tribunal": ["OSNOVNI SUD U BEOGRADU", "Osnovni sud u Beogradu"],
        "case number or case identifier": ["K. br. 245/23"],
        "judge or judicial officer": ["Marija Nikolić"],
        "court registrar or clerk": ["Ane Stojanović"],
        "defendant or accused person": ["MILOŠA PETROVIĆA", "MILOŠ PETROVIĆ"],
        "prosecutor or public attorney": ["Dragana Milovanovića"],
        "criminal act or offense": ["krađe"],
        "material legal provision or article": ["člana 203. stav 1. Krivičnog zakonika"],
        "type of sanction or penalty": ["novčanu kaznu"],
        "sanction amount or duration": ["30.000 dinara"],
        "legal procedure costs or fees": ["5.000 dinara"]
    },
    "example_02_assault.txt": {
        "court or tribunal": ["VIŠI SUD U NOVOM SADU", "Viši sud u Novom Sadu"],
        "case number or case identifier": ["Kž. 1567/22", "K. br. 892/22"],
        "judge or judicial officer": ["Aleksandar Jovanović", "Milica Radović", "Petar Stanković"],
        "court registrar or clerk": ["Jovane Mitrović"],
        "defendant or accused person": ["STEFANA MARKOVIĆA", "STEFAN MARKOVIĆ"],
        "prosecutor or public attorney": ["Milana Đorđevića"],
        "criminal act or offense": ["nasilničko ponašanje"],
        "material legal provision or article": ["člana 344. stav 1. Krivičnog zakonika"],
        "type of sanction or penalty": ["kazna zatvora"],
        "sanction amount or duration": ["6 meseci", "2 godine"]
    },
    "example_03_fraud.txt": {
        "court or tribunal": ["OSNOVNI SUD U KRAGUJEVCU", "Osnovni sud u Kragujevcu"],
        "case number or case identifier": ["K. br. 1123/23"],
        "judge or judicial officer": ["dr Jelena Milosavljević"],
        "court registrar or clerk": ["Nemanje Stojanovića"],
        "defendant or accused person": ["ANJE STOJANOVIĆ", "ANJA STOJANOVIĆ"],
        "prosecutor or public attorney": ["Srđana Petrovića"],
        "criminal act or offense": ["prevare"],
        "material legal provision or article": ["člana 208. stav 1. Krivičnog zakonika"],
        "type of sanction or penalty": ["kaznu zatvora"],
        "sanction amount or duration": ["8 meseci", "2 godine"],
        "legal procedure costs or fees": ["12.000 dinara"]
    },
    "example_04_traffic.txt": {
        "court or tribunal": ["PREKRŠAJNI SUD U NIŠU", "Prekršajni sud u Nišu"],
        "case number or case identifier": ["Pr. br. 3456/23"],
        "judge or judicial officer": ["Marko Đorđević"],
        "court registrar or clerk": ["Tanje Nikolić"],
        "defendant or accused person": ["VLADIMIRA MILENKOVIĆA", "VLADIMIR MILENKOVIĆ"],
        "criminal act or offense": ["prekršaja"],
        "material legal provision or article": ["člana 330. stav 1. tačka 3. Zakona o bezbednosti saobraćaja na putevima"],
        "type of sanction or penalty": ["novčanom kaznom", "ZAŠTITNA MERA zabrane upravljanja motornim vozilom"],
        "sanction amount or duration": ["80.000 dinara", "8 meseci"],
        "legal procedure costs or fees": ["3.000 dinara"]
    },
    "example_05_drug_possession.txt": {
        "court or tribunal": ["OSNOVNI SUD U SUBOTICI", "Osnovni sud u Subotici"],
        "case number or case identifier": ["K. br. 567/23"],
        "judge or judicial officer": ["Ana Popović"],
        "court registrar or clerk": ["Milana Jovanovića"],
        "defendant or accused person": ["NIKOLE RADIĆA", "NIKOLA RADIĆ"],
        "prosecutor or public attorney": ["Marije Stanković"],
        "criminal act or offense": ["neovlašćena proizvodnja i stavljanje u promet opojnih droga"],
        "material legal provision or article": ["člana 246a stav 1. Krivičnog zakonika"],
        "type of sanction or penalty": ["kaznu zatvora"],
        "sanction amount or duration": ["6 meseci", "1 godine"],
        "legal procedure costs or fees": ["8.000 dinara"]
    },
    "example_06_domestic_violence.txt": {
        "court or tribunal": ["OSNOVNI SUD U PANČEVU", "Osnovni sud u Pančevu"],
        "case number or case identifier": ["K. br. 789/23"],
        "judge or judicial officer": ["Gordana Milić"],
        "court registrar or clerk": ["Jovana Petrovića"],
        "defendant or accused person": ["ZORANA MILOVIĆA", "ZORAN MILOVIĆ"],
        "prosecutor or public attorney": ["Dragice Nikolić"],
        "criminal act or offense": ["nasilje u porodici"],
        "material legal provision or article": ["člana 194. stav 2. Krivičnog zakonika"],
        "type of sanction or penalty": ["kaznu zatvora", "ZAŠTITNA MERA zabrane prilaska"],
        "sanction amount or duration": ["10 meseci", "1 godine"],
        "legal procedure costs or fees": ["15.000 dinara"]
    },
    "example_07_embezzlement.txt": {
        "court or tribunal": ["VIŠI SUD U ČAČKU", "Viši sud u Čačku"],
        "case number or case identifier": ["K. br. 234/22"],
        "judge or judicial officer": ["dr Milan Stojanović", "Vesna Marković", "Dragan Nikolić"],
        "court registrar or clerk": ["Milice Jovanović"],
        "defendant or accused person": ["MILORADA PETROVIĆA", "MILORAD PETROVIĆ"],
        "prosecutor or public attorney": ["Aleksandra Milovanovića"],
        "criminal act or offense": ["pronevere"],
        "material legal provision or article": ["člana 364. stav 3. Krivičnog zakonika"],
        "type of sanction or penalty": ["kaznu zatvora"],
        "sanction amount or duration": ["3 godine"],
        "legal procedure costs or fees": ["45.000 dinara"]
    },
    "example_08_tax_evasion.txt": {
        "court or tribunal": ["OSNOVNI SUD U LESKOVCU", "Osnovni sud u Leskovcu"],
        "case number or case identifier": ["K. br. 445/23"],
        "judge or judicial officer": ["Milena Stanković"],
        "court registrar or clerk": ["Nemanje Milovanovića"],
        "defendant or accused person": ["RADOSLAVA ĐORĐEVIĆA", "RADOSLAV ĐORĐEVIĆ"],
        "prosecutor or public attorney": ["Jovane Petrović"],
        "criminal act or offense": ["poreska utaja"],
        "material legal provision or article": ["člana 229. stav 2. Krivičnog zakonika"],
        "type of sanction or penalty": ["kaznu zatvora"],
        "sanction amount or duration": ["1 godine i 6 meseci", "3 godine"],
        "legal procedure costs or fees": ["25.000 dinara"]
    },
    "example_09_robbery.txt": {
        "court or tribunal": ["OSNOVNI SUD U ZRENJANINU", "Osnovni sud u Zrenjaninu"],
        "case number or case identifier": ["K. br. 678/23"],
        "judge or judicial officer": ["Bojan Marković"],
        "court registrar or clerk": ["Ane Milenković"],
        "defendant or accused person": ["MARKA JOVANOVIĆA", "STEFANA NIKOLIĆA", "MARKO JOVANOVIĆ", "STEFAN NIKOLIĆ"],
        "prosecutor or public attorney": ["Milice Đorđević"],
        "criminal act or offense": ["razbojništva"],
        "material legal provision or article": ["člana 206. stav 1. Krivičnog zakonika"],
        "type of sanction or penalty": ["kaznu zatvora"],
        "sanction amount or duration": ["2 godine", "1 godine i 8 meseci"],
        "legal procedure costs or fees": ["30.000 dinara"]
    },
    "example_10_corruption.txt": {
        "court or tribunal": ["VIŠI SUD U UŽICU", "Viši sud u Užicu"],
        "case number or case identifier": ["K. br. 123/22"],
        "judge or judicial officer": ["dr Marija Jovanović", "Aleksandar Petrović", "Milica Nikolić"],
        "court registrar or clerk": ["Dragana Milovanovića"],
        "defendant or accused person": ["VLADIMIRA STANKOVIĆA", "VLADIMIR STANKOVIĆ"],
        "prosecutor or public attorney": ["Ane Đorđević"],
        "criminal act or offense": ["primanja mita"],
        "material legal provision or article": ["člana 367. stav 2. Krivičnog zakonika"],
        "type of sanction or penalty": ["kaznu zatvora", "SPOREDNA KAZNA zabrane vršenja javne funkcije"],
        "sanction amount or duration": ["4 godine", "3 godine"],
        "legal procedure costs or fees": ["60.000 dinara"]
    }
}
