[project]
name = "montenegro-court-scraper"
version = "0.1.0"
description = "Playwright-based scraper for Montenegro court decisions"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "playwright>=1.55.0",
]
